---
knit: "bookdown::render_book"
---

# Acknowledgements {-}

I would like to express my deepest gratitude to my supervisors, Lauren Kennedy and Shiro Kuriwaki. They have given me so much time, knowledge, wisdom, and patience since I started until I finished this thesis. Their continuous feedback, guidance, encouragement, and advice were like a light in the dark, especially when this thesis became increasingly challenging to complete. 

I would like to extend my gratitude to Dan Simpson, the chief examiner of Master of Business Analytics and Creative Activity, for all the guidance in completing this unit.

I also would like to thank Australia Awards Scholarship for giving me the scholarship to study at the Monash University. Without it, studying in Australia would only remain as one of my childhood dreams.

Last but not least, I dedicated this thesis to my late father, who always gave me unconditional love and support in pursuing my dreams. 

## R packages {-}

Several R [@R] packages are utilized to produce this thesis: `mrpkit` [@mrpkit]; `ccesMRPprep` [@ccesmrpprep]; `brms` [@brms]; `cmdstanr` [@cmdstanr]; `ddi` [@ddi];`survey` [@survey]; `tidyverse` [@tidyverse]; `forcats` [@forcats]; `Metrics` [@Metrics]; `data.table` [@datatable]; `kableExtra` [@kable]; `janitor` [@janitor]; `scales` [@scales]; `ggplot2` [@ggplot2]; `patchwork` [@pw]; `flipPlots` [@flipflops]; `igraph` [@igraph]; `urbnmapr` [@urban]; `ggstance` [@stance]; `ggpmisc` [@ggpmisc]; `wacolors` [@wacolors]; `rmarkdown` [@rmd]; `knitr` [@knitr]; `MonashEBSTemplates` [@monashtemp]. 











