---
chapter: 4
knit: "bookdown::render_book"
---

```{r setup-chap4, include=FALSE, cache=FALSE}
library(knitr)
```

# Conclusion {#ch:conclusion}

Graphical displays are essential to explore and understand data and model fits. They have been widely used to communicate and diagnose MRP models. However, there have been few studies formally investigating the use of visualisation within an MRP context. Therefore, in this study, we conduct a systematic literature review to understand the current practice in MRP visualisation. In addition, we perform a case study using the Cooperative and Congressional Election Study (CCES) to demonstrate the implication of current visualisation practices and explore the alternatives and possible improvements. 

We find that the choropleth map is the most frequently used visualisation to communicate MRP estimates. However, it is problematic as it often hinders the information in small geographic areas and does not consider the uncertainty of estimates. Instead, we explore alternatives to display state-wise estimates using a dot plot with an error bar. 
Even though it is important to show estimate uncertainty, in our literature review, we find few plots actually displayed it. We propose some alternatives to display uncertainty, for example, using a violin plot. This study also demonstrates how graphs have aided us in understanding how methods and modeling choices affect the estimates. We also use credible interval length to illustrate the bias-variance trade-off. 

Naturally, this study has some limitations. In the CCES case study, none of the MRP models perform as well as the weighted estimates. However, this allowed us to demonstrate the use of visualisation to compare models that had different types of errors (such as bias or variance). Future work could compare the use of the visualisation proposed with an accurate model. 

Another limitation is this study only explores alternatives to MRP visualisation in a case study. While this was useful for this study because it helped us to see the differences between visualisations, it does not conclusively provide evidence these alternatives can communicate more effectively and enhance interpretability. To get evidence of this, future work should employ careful experimentation. One example of this would be showing different types of graphs to people and seeing which aids the most accurate interpretation. 


This study has provided empirical evidence on how visualisation has been performed in MRP research. One use of these findings is as a starting point to continue to explore alternative visualisations, such as those proposed in Chapter \@ref(ch:case-stud). Another use is to provide inspiration for MRP users in their own work and research. Finally, this work highlights the importance of including uncertainty which was not being included in practice. 



